server:
  port: 8080
  tomcat:
    uri-encoding: UTF-8
spring:
  main:
    allow-bean-definition-overriding: true #当遇到同样名字的时候，是否允许覆盖注册
  profiles:
    active: native
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  messages:
    encoding: UTF-8
#mybatis配置
mybatis:
  type-aliases-package: cn.ykthink.jewelry.model
  mapper-locations: classpath:mybatis/mapper/pc/*.xml
  configLocation: classpath:mybatis/mybatis-config.xml
jewelry:
  jwt:
    key: jewelry2019