server:
  port: 8080
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://39.108.132.170:3306/jewelry?serverTimezone=UTC&useSSL=false
    username: root
    password: fyk159753
    driver-class-name: com.mysql.jdbc.Driver
    #连接池配置
    #获得连接后检测其可用性
    test-on-borrow: true
    # 初始化大小，最小，最大
    initialSize: 5
    minIdle: 5
    maxActive: 20
    # 配置获取连接等待超时的时间
    maxWait: 60000
    # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    timeBetweenEvictionRunsMillis: 60000
    # 配置一个连接在池中最小生存的时间，单位是毫秒
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    useGlobalDataSourceStat: true
    # 配置监控统计拦截的filters，去掉后监控界面sql将无法统计，'wall'用于防火墙
    filters: stat
    # 通过connectProperties属性来打开mergeSql功能，慢SQL记录
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
  #redis配置 redis-01 localhost redis-stage redis
  redis:
    database: 1
    host: 39.108.132.170
    port: 6379
    password: fyk159753
    timeout: 1000ms
    jedis:
      pool:
        max-active: 1024
        max-idle: 200
        min-idle: 50
        max-wait: 1000ms
