server:
  port: 8080
  tomcat:
    uri-encoding: UTF-8
spring:
  profiles:
    active: native
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  messages:
    encoding: UTF-8
#mybatis配置
mybatis:
  type-aliases-package: cn.ykthink.jewelry.model
  mapper-locations: classpath:mybatis/mapper/pc/*.xml,classpath:mybatis/mapper/cms/*.xml,classpath:mybatis/mapper/common/*.xml
  configLocation: classpath:mybatis/mybatis-config.xml
#分页插件配置
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
jewelry:
  jwt:
    key: jewelry2019
  pages:
    page_index: 1
    page_size: 10
  tx:
    appId: 1400217435
    appKey: 8a0a933fcad0c10d437c7748f7370f29
    countryCode: 86
  qny:
    accessKey: ojc77Gx5YGcmrVIZGOsU9FeagvKntkGkF_7qaSZP
    secretKey: -JeHOwkXUSHsCYxhEwXwq3MJOoU86fbE_tU5UDu9
    bucket: jewelry
    cdnUrl: cdn-jewelry.ykthink.cn